stages:
  Data_Collection:
    cmd: python src/data_collection.py
    deps:
      - src/data_collection.py
      - Churn_Data/Demographics.xlsx
      - Churn_Data/Location.xlsx
      - Churn_Data/Population.xlsx
      - Churn_Data/Services.xlsx
      - Churn_Data/Status.xlsx
    outs:
      - data/raw/train.csv
      - data/raw/test.csv

  Data_Preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv
      - preprocessor.pkl:
          cache: false

  Model_Training:
    cmd: python src/model_training.py --model-type all
    deps:
      - src/model_training.py
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv
    params:
      - model
    outs:
      - model.pkl:
          cache: false
      - .mlflow_run_id:
          cache: false

  Evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - model.pkl
      - preprocessor.pkl
      - .mlflow_run_id
    outs:
      - metrics.json:
          cache: false